!coverage.py: This is a private format, don't read it directly!{"lines":{"/home/vsmysle/dev/pyfile.io/fileio/__init__.py":[1,2],"/home/vsmysle/dev/pyfile.io/fileio/api.py":[1,2,3,4,5,6,7,9,10,13,14,16,29,74,95,135,167,194,214,226,241,22,23,24,25,26,27,41,43,45,47,49,51,52,53,206,211,212,57,62,63,65,66,67,68,69,70,71,86,181,182,183,191,192,87,88,89,251,252,90,224,91,236,237,238,239,92,93,184,186,190,104,106,108,110,112,113,114,122,124,125,126,128,130,109,132,133,111,116,117,146,147,150,154,156,159,160,161,162,151,165,185,187,188],"/home/vsmysle/dev/pyfile.io/fileio/models.py":[1,2,3,6,7,9,27,34,45,49,11,12,14,15,16,17,25,36,37,38,39,40,41,42,47,51],"/home/vsmysle/dev/pyfile.io/fileio/exceptions.py":[1,4,9,10,13,17,18]}}