!coverage.py: This is a private format, don't read it directly!{"lines":{"/home/vsmysle/dev/pyfile.io/fileio/__init__.py":[1,2],"/home/vsmysle/dev/pyfile.io/fileio/api.py":[1,2,3,4,5,6,7,9,10,13,14,16,29,81,102,142,174,201,221,233,245,257,272,286,22,23,24,25,26,27,41,43,45,47,49,51,52,53,213,218,219,57,62,63,66,69,72,295,296,75,76,77,78,79,297,299,300,93,188,189,190,198,199,94,95,96,282,283,97,231,98,267,268,269,270,99,100,191,193,197,111,113,115,117,119,120,121,129,131,132,133,135,137,116,139,140,118,123,124,153,154,157,161,163,166,167,168,169,158,172,192,194,195],"/home/vsmysle/dev/pyfile.io/fileio/models.py":[1,2,3,6,7,9,27,34,45,49,11,12,14,15,16,17,25,36,37,38,39,40,41,42,47,51],"/home/vsmysle/dev/pyfile.io/fileio/exceptions.py":[1,4,9,10,13,17,18,21,25,26]}}